### ISSUE TITLE
generator needs to run every time the bower_components dir is cleared. 

### ISSUE THREAD

**Issue by DanielOchoa** [poetic/ember-cli-photoswipe#10]
Right now, `ember g photoswipe` needs to run every time the bower_components/photoswipe directory is removed or regenerated. This is because the addon creates a custom build of photoswipe without the history module, given that it breaks ember routing. 

It would be nice if the generator does not need to be run every time this happens.

**Comment by imtapps** [comment]
#13 Fixes this issue.
