### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'initialLayout' of false

### ISSUE THREAD

**Issue by blisst** [poetic/ember-cli-photoswipe#17]
Can't use the addon, ember-cli@0.2.7

When I click a thumbnail I get `Uncaught TypeError: Cannot assign to read only property 'initialLayout' of false`.

Offending code:

```
_registerModule('Controller', {
    ....
    _listen('initialLayout', function() {
                self.currItem.initialLayout = _options.getThumbBoundsFn && _options.getThumbBoundsFn(_currentItemIndex);
            });

```

My template: 

```
{{#photo-swipe}}
      {{#each model.bar.photos as |image|}}
        <a class="photo-item" href="{{image.url}}" data-width="{{image.width}}" data-height="{{image.height}}">
          <img src="{{image.url}}" alt="" />
        </a>
      {{/each}}
{{/photo-swipe}}
```

**Comment by DanielOchoa** [comment]
Interesting. The offending code is not part of the addon. If you remove the photoswipe component and just iterate over the photos on the template, are you able to make the the photos render?

**Comment by blisst** [comment]
Yes I was previously rendering the photos with no problems, using `fancyBox` till I found out fancyBox doesn't have swipe support.

**Comment by blisst** [comment]
Wait so you closed it because it is an issue not with the add-on?  It's definitely something to do with Photoswipe.

**Comment by DanielOchoa** [comment]
I wasn't able to reproduce it on a new ember-cli app with that version

**Comment by iamjstates** [comment]
@blisst - did you ever fix this problem. I'm having the same issue

**Comment by edborden** [comment]
Also seeing this (ember@2.3,ember-cli@2.3).... Only reference I can find is https://github.com/dimsemenov/PhotoSwipe/issues/1041, with no fix

**Comment by blisst** [comment]
I apologize I haven't been working in Ember for a while now and thus don't remember what ended up happening...

**Comment by edborden** [comment]
I figured it out. Basically, I was passing an arrays of `image` models to the component, where the component requires an array of vanilla js objects. Since that array gets passed straight through, PhotoSwipe was choking on it.

**Comment by rogyvoje** [comment]
I got the same error when I passed an empty array. Make sure you are sending images to the photo swipe.
