### ISSUE TITLE
Update readme / package be compatible with `install:addon`

### ISSUE THREAD

**Issue by jakecraige** [poetic/ember-cli-photoswipe#2]
Readme should say

``` js
ember install:addon ember-cli-photoswipe
```

The package.json would need to be updated to have the `defaultBlueprint` specified as `photoswipe` so that this will automatically run the generator for you

**Comment by DanielOchoa** [comment]
good catch

**Comment by DanielOchoa** [comment]
Commit 7450da2a10d73e922cf4b3841c0231e0c99a51f6 adds this feature. Thanks!
