### ISSUE TITLE
Addon does not work as advertised

### ISSUE THREAD

**Issue by davidgoli** [poetic/ember-cli-photoswipe#27]
This is a deeper issue perhaps, but one that basically cripples this addon for use in Ember 2.0. This is based on the workarounds found in https://github.com/poetic/ember-cli-photoswipe/issues/26.
- Render a template containing the `photo-swipe` component with some photos nested inside
- Update the model that contains the photos
- Click on the `photo-swipe` component to open the gallery

Result: The old model's photos are displayed, not the new model's
This is because the `photo-swipe` component is not compatible with Glimmer and Ember 1.13+. Rather than relying on model bindings on the component, it depends on the `didInsertElement` hook to inspect its contents. This is a big no-no in Glimmer, as this hook is not guaranteed to fire when the contents have changed.

Additionally, these workarounds contradict the documented usage of the addon based on the README. In fact, the addon's own code marks the usage of the `items` argument as deprecated. I would strongly recommend restoring the `items` argument and yielding the individual items as a block.

**Comment by davidgoli** [comment]
@osxi Is this addon even still maintained? Ember has moved on and this addon needs to keep pace with bugfixes. If not, I'd happily take on ownership.

**Comment by davidgoli** [comment]
I didn't really understand what was going on here until I dived into the code further. It appears using the component WITHOUT `items` is what's deprecated, which is not at all clear in the documentation. See #28 for a doc fix.

**Comment by davidgoli** [comment]
It appears that the published version of this addon `1.1.0` is well behind `master` in this repository. The fix is to publish a new version based on `master`.

**Comment by MatthewHager** [comment]
@davidgoli woudl you be down to help maintain if I add you as a collaborator?

**Comment by davidgoli** [comment]
Yes! Just pushed v1.2.0. However, I can't npm publish because I don't have
permission. Would someone on your end either give me access or just run npm
publish from latest master?

Thanks!

**Comment by MatthewHager** [comment]
@davidgoli added you on NPM. Thanks for pitching in! Feel free to PR the readme and give yourself comaintainer/contributor credit.

**Comment by davidgoli** [comment]
Fixed with https://github.com/poetic/ember-cli-photoswipe/pull/28
