### ISSUE TITLE
Using ember-cli-photoswipe without an 'items' attribute is deprecated.

### ISSUE THREAD

**Issue by aalpizar** [poetic/ember-cli-photoswipe#34]
So I'm using the example code/data to try to get this working, and I keep getting these two errors. I'm using the button action approach that opens the gallery.

`Using ember-cli-photoswipe without an items attribute is deprecated.` and
`Cannot read property 'init' of undefined`  (in regards to `this.get('myGallery').init();`)

this is what the code looks like

```
//handlebars
<button class="btn" {{action 'initGallery'}}>Open PhotoSwipe</button>
 {{photo-swipe gallery=myGallery options=psOpts items=items}}

//component
 psOpts: {  
   index: 1
 },
items: [
    {
      src: 'http://placekitten.com/g/600/400',
      w: 600,
      h: 400,
      title: 'whooa'
    },
    {
      src: 'http://placekitten.com/g/1200/900',
      w: 1200,
      h: 900
    }
  ]

actions: {
   initGallery() {
      this.get('myGallery').init();
    }
}
```

**Comment by davidgoli** [comment]
I just tested your code on a clean project, and I'm unable to reproduce this error. Can you please confirm that the handlebars template is named the same as the component that contains your component code? The deprecation warning you mention appears when the `items` property is "falsy", which would be the case if your definition of `items` isn't in scope in the template. (The exact check is `if (this.get('items'))`.)
