### ISSUE TITLE
Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by Mannaio** [poetic/ember-cli-photoswipe#7]
I am trying to set ember-cli.photoswipe locally and i come across to these issues

Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
Symbol.hasOwnProperty 

Symbols don't coerce to strings on their own

![schermata 2015-03-15 alle 18 09 52](https://cloud.githubusercontent.com/assets/1617078/6657034/c7b2c1ce-cb3e-11e4-86e9-ce737621a027.png)

after all these steps
- git clone https://github.com/DanyHunter/ember-cli-photoswipe.git
- ember install:addon ember-cli-photoswipe
- ember server
  
  My ember cli version is : "ember-cli": "0.1.7"

How can i sort it out?

**Comment by DanielOchoa** [comment]
In order to run the dummy app, you don't need to run `ember install:addon ember-cli-photoswipe`. 

All you need to do is:
1. Clone repo
2. npm install && bower install
3. ember g photoswipe

ember install:addon downloads an addon from npm for you and runs the generator. Because you are cloning the repo you just need to run the generator using `ember g photoswipe`. Hope that helps.

**Comment by Mannaio** [comment]
ok, i have done like this

Installed node v0.11.14 by NVM

npm install -g ember-cli
npm install -g bower
git clone https://github.com/poetic/ember-cli-photoswipe.git

in my ember-cli-photoswipe path

npm install && bower install
ember g photoswipe

This is the error msg now
![schermata 2015-03-16 alle 22 53 31](https://cloud.githubusercontent.com/assets/1617078/6677343/548d3d22-cc2f-11e4-9adb-384885e3ddb9.png)

**Comment by DanielOchoa** [comment]
Do you have ember-cli installed? `npm install ember-cli -g`

I haven't tested it, but as long as you run `npm install` inside the project dir, it should set up everything correctly even if you don't have ember-cli globally installed.

**Comment by Mannaio** [comment]
yes! i have updated my comment

**Comment by DanielOchoa** [comment]
Ah, this seems to be an issue https://github.com/ember-cli/ember-cli/issues/3492 that occurs on previous versions of ember-cli. ( I should probably update the addon to the newest release). 

Can you try the following? 
In your `package.json` add `"rimraf": "2.2.8"` and make sure glob is locked down to 4.0.5 (`"glob": "4.0.5"`)
These are under devDependencies by the way

**Comment by Mannaio** [comment]
ok done it but it looks like not solving it, i attached my steps

first

adding "rimraf": "2.2.8"

![schermata 2015-03-16 alle 23 10 32](https://cloud.githubusercontent.com/assets/1617078/6677626/1f05ae34-cc32-11e4-88f1-2d64842f59a1.png)

then  npm install 

![schermata 2015-03-16 alle 23 10 09](https://cloud.githubusercontent.com/assets/1617078/6677634/2ded2b2a-cc32-11e4-8ffa-30e69a56cf11.png)

**Comment by DanielOchoa** [comment]
Well, this is not good at all. 
I found this. https://github.com/ember-cli/ember-cli/issues/3413#issuecomment-77104018 At some point I ran into this same error but I can't duplicate. 

My bad, rimraf should be specified under `dependencies` and not `devDependencies`

Also, it would probably help if you remove the node_modules directory and run `npm cache clean`, then npm install again, and ember serve afterwards.

**Comment by DanyHunter** [comment]
Either way, I'll upgrade the addon's ember-cli version tonight so this problem will go away. Thanks for your patience.

**Comment by Mannaio** [comment]
You hit the spot, it started working with your recommendations

'remove the node_modules directory and run npm cache clean'

You can close it

Cool

**Comment by DanielOchoa** [comment]
good to hear
